#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - curl

runcmd:
  # Download and install Go
  - curl -OL https://go.dev/dl/go1.22.6.linux-amd64.tar.gz
  - tar -C /usr/local -xzf go1.22.6.linux-amd64.tar.gz
  - echo "export PATH=$PATH:/usr/local/go/bin" >> /etc/profile
  - source /etc/profile

  # Clone the GitHub repository
  - git clone https://github.com/gvicentin/inf0500.git /opt/inf0500

  # Navigate to the repository directory
  - cd /opt/inf0500/inf0554

  # Run the Go application
  - make compile
  - ./demo
